// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCBuilder.Data;

#nullable disable

namespace PCBuilder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PCBuilder.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Builds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 4, 23, 12, 16, 48, 555, DateTimeKind.Utc).AddTicks(2938),
                            Description = "Montagem essencial para entrar no mundo dos games com excelente custo-benefício. Roda os maiores títulos em alta qualidade.",
                            IsCustom = false,
                            IsTemplate = true,
                            Name = "PC Gamer Base"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 4, 23, 12, 16, 48, 555, DateTimeKind.Utc).AddTicks(2945),
                            Description = "Performance de alto nível para jogos em 1440p e 4K. Overclock ready, preparado para os games mais exigentes do mercado.",
                            IsCustom = false,
                            IsTemplate = true,
                            Name = "PC Gamer Pro"
                        },
                        new
                        {
                            Id = 3,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 4, 23, 12, 16, 48, 555, DateTimeKind.Utc).AddTicks(2946),
                            Description = "Máquina de trabalho para edição de vídeo 4K, modelagem 3D, machine learning e renderização profissional.",
                            IsCustom = false,
                            IsTemplate = true,
                            Name = "PC Workstation"
                        });
                });

            modelBuilder.Entity("PCBuilder.Models.BuildComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("ProductId");

                    b.ToTable("BuildComponents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildId = 1,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            BuildId = 1,
                            ProductId = 10,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            BuildId = 1,
                            ProductId = 20,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            BuildId = 1,
                            ProductId = 30,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            BuildId = 1,
                            ProductId = 40,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            BuildId = 1,
                            ProductId = 51,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            BuildId = 1,
                            ProductId = 60,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 8,
                            BuildId = 2,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            BuildId = 2,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            BuildId = 2,
                            ProductId = 21,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 11,
                            BuildId = 2,
                            ProductId = 31,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 12,
                            BuildId = 2,
                            ProductId = 43,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 13,
                            BuildId = 2,
                            ProductId = 52,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 14,
                            BuildId = 2,
                            ProductId = 62,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 15,
                            BuildId = 3,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 16,
                            BuildId = 3,
                            ProductId = 15,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 17,
                            BuildId = 3,
                            ProductId = 24,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 18,
                            BuildId = 3,
                            ProductId = 32,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 19,
                            BuildId = 3,
                            ProductId = 42,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 20,
                            BuildId = 3,
                            ProductId = 53,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 21,
                            BuildId = 3,
                            ProductId = 63,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("PCBuilder.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PCBuilder.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PCBuilder.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChipsetCompatibility")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PowerConsumption")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Socket")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TDP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WattageCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "AMD",
                            Description = "6-core, 12-thread, 3.7GHz boost 4.6GHz",
                            IsAvailable = true,
                            Name = "Ryzen 5 5600X",
                            PowerConsumption = 65,
                            Price = 999m,
                            Socket = "AM4",
                            TDP = 65,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "AMD",
                            Description = "8-core com 3D V-Cache, ideal para games",
                            IsAvailable = true,
                            Name = "Ryzen 7 5800X3D",
                            PowerConsumption = 105,
                            Price = 1799m,
                            Socket = "AM4",
                            TDP = 105,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Brand = "AMD",
                            Description = "16-core, workstation e criação de conteúdo",
                            IsAvailable = true,
                            Name = "Ryzen 9 7950X",
                            PowerConsumption = 170,
                            Price = 3899m,
                            Socket = "AM5",
                            TDP = 170,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Intel",
                            Description = "14-core (6P+8E), excelente custo-benefício",
                            IsAvailable = true,
                            Name = "Core i5-13600K",
                            PowerConsumption = 125,
                            Price = 1299m,
                            Socket = "LGA1700",
                            TDP = 125,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Intel",
                            Description = "16-core, alto desempenho gamer e produtividade",
                            IsAvailable = true,
                            Name = "Core i7-13700K",
                            PowerConsumption = 125,
                            Price = 2199m,
                            Socket = "LGA1700",
                            TDP = 125,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Intel",
                            Description = "24-core, flagship Intel para workstation",
                            IsAvailable = true,
                            Name = "Core i9-13900K",
                            PowerConsumption = 253,
                            Price = 3499m,
                            Socket = "LGA1700",
                            TDP = 253,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Brand = "AMD",
                            Description = "8GB GDDR6, 1080p gaming",
                            IsAvailable = true,
                            Name = "RX 6600 XT",
                            PowerConsumption = 160,
                            Price = 1299m,
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Brand = "AMD",
                            Description = "12GB GDDR6, 1440p gaming",
                            IsAvailable = true,
                            Name = "RX 6700 XT",
                            PowerConsumption = 230,
                            Price = 1999m,
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Brand = "AMD",
                            Description = "24GB GDDR6, flagship 4K",
                            IsAvailable = true,
                            Name = "RX 7900 XTX",
                            PowerConsumption = 355,
                            Price = 5499m,
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Brand = "NVIDIA",
                            Description = "8GB GDDR6X, 1080p/1440p gaming",
                            IsAvailable = true,
                            Name = "RTX 3060 Ti",
                            PowerConsumption = 200,
                            Price = 1799m,
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Brand = "NVIDIA",
                            Description = "12GB GDDR6X, excelente 1440p",
                            IsAvailable = true,
                            Name = "RTX 4070",
                            PowerConsumption = 200,
                            Price = 3199m,
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Brand = "NVIDIA",
                            Description = "24GB GDDR6X, melhor GPU para 4K e criação",
                            IsAvailable = true,
                            Name = "RTX 4090",
                            PowerConsumption = 450,
                            Price = 9999m,
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Corsair",
                            Description = "Kit 2x8GB, CL16",
                            IsAvailable = true,
                            Name = "16GB DDR4 3200MHz",
                            PowerConsumption = 5,
                            Price = 299m,
                            Type = 2
                        },
                        new
                        {
                            Id = 21,
                            Brand = "G.Skill",
                            Description = "Kit 2x16GB, CL18, Trident Z",
                            IsAvailable = true,
                            Name = "32GB DDR4 3600MHz",
                            PowerConsumption = 10,
                            Price = 549m,
                            Type = 2
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Kingston",
                            Description = "Kit 4x16GB, para workstations",
                            IsAvailable = true,
                            Name = "64GB DDR4 3200MHz",
                            PowerConsumption = 15,
                            Price = 999m,
                            Type = 2
                        },
                        new
                        {
                            Id = 23,
                            Brand = "G.Skill",
                            Description = "Kit 2x16GB, DDR5 alta performance",
                            IsAvailable = true,
                            Name = "32GB DDR5 6000MHz",
                            PowerConsumption = 10,
                            Price = 849m,
                            Type = 2
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Corsair",
                            Description = "Kit 2x32GB, workstation DDR5",
                            IsAvailable = true,
                            Name = "64GB DDR5 5600MHz",
                            PowerConsumption = 15,
                            Price = 1599m,
                            Type = 2
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Samsung",
                            Description = "970 EVO Plus, 3500MB/s leitura",
                            IsAvailable = true,
                            Name = "SSD NVMe 500GB",
                            PowerConsumption = 5,
                            Price = 299m,
                            Type = 3
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Samsung",
                            Description = "980 PRO, 7000MB/s PCIe 4.0",
                            IsAvailable = true,
                            Name = "SSD NVMe 1TB",
                            PowerConsumption = 6,
                            Price = 499m,
                            Type = 3
                        },
                        new
                        {
                            Id = 32,
                            Brand = "WD",
                            Description = "Black SN850X, 7300MB/s PCIe 4.0",
                            IsAvailable = true,
                            Name = "SSD NVMe 2TB",
                            PowerConsumption = 7,
                            Price = 899m,
                            Type = 3
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Seagate",
                            Description = "BarraCuda, 7200RPM, armazenamento extra",
                            IsAvailable = true,
                            Name = "HDD 2TB SATA",
                            PowerConsumption = 8,
                            Price = 249m,
                            Type = 3
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Gigabyte",
                            ChipsetCompatibility = "AM4",
                            Description = "Micro-ATX, DDR4, PCIe 4.0",
                            IsAvailable = true,
                            Name = "B550M DS3H",
                            PowerConsumption = 30,
                            Price = 599m,
                            Socket = "AM4",
                            Type = 4
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Gigabyte",
                            ChipsetCompatibility = "AM4",
                            Description = "ATX, DDR4, PCIe 4.0, WiFi",
                            IsAvailable = true,
                            Name = "X570 AORUS Elite",
                            PowerConsumption = 35,
                            Price = 999m,
                            Socket = "AM4",
                            Type = 4
                        },
                        new
                        {
                            Id = 42,
                            Brand = "ASRock",
                            ChipsetCompatibility = "AM5",
                            Description = "ATX, DDR5, PCIe 5.0, flagship AM5",
                            IsAvailable = true,
                            Name = "X670E Taichi",
                            PowerConsumption = 40,
                            Price = 2499m,
                            Socket = "AM5",
                            Type = 4
                        },
                        new
                        {
                            Id = 43,
                            Brand = "MSI",
                            ChipsetCompatibility = "LGA1700",
                            Description = "ATX, DDR4, PCIe 5.0",
                            IsAvailable = true,
                            Name = "Z690 Tomahawk DDR4",
                            PowerConsumption = 35,
                            Price = 1099m,
                            Socket = "LGA1700",
                            Type = 4
                        },
                        new
                        {
                            Id = 44,
                            Brand = "MSI",
                            ChipsetCompatibility = "LGA1700",
                            Description = "ATX, DDR5, PCIe 5.0, flagship Z790",
                            IsAvailable = true,
                            Name = "Z790 ACE",
                            PowerConsumption = 40,
                            Price = 2199m,
                            Socket = "LGA1700",
                            Type = 4
                        },
                        new
                        {
                            Id = 50,
                            Brand = "Corsair",
                            Description = "Semi-modular, proteções completas",
                            IsAvailable = true,
                            Name = "CV550 550W 80+ Bronze",
                            PowerConsumption = 0,
                            Price = 399m,
                            Type = 5,
                            WattageCapacity = 550
                        },
                        new
                        {
                            Id = 51,
                            Brand = "Corsair",
                            Description = "Fully modular, silencioso",
                            IsAvailable = true,
                            Name = "RM750x 750W 80+ Gold",
                            PowerConsumption = 0,
                            Price = 699m,
                            Type = 5,
                            WattageCapacity = 750
                        },
                        new
                        {
                            Id = 52,
                            Brand = "Corsair",
                            Description = "Fully modular, ideal para RTX 4080/4090",
                            IsAvailable = true,
                            Name = "RM850x 850W 80+ Gold",
                            PowerConsumption = 0,
                            Price = 849m,
                            Type = 5,
                            WattageCapacity = 850
                        },
                        new
                        {
                            Id = 53,
                            Brand = "Corsair",
                            Description = "Modular, certificado Platinum, workstation",
                            IsAvailable = true,
                            Name = "HX1000 1000W 80+ Plat",
                            PowerConsumption = 0,
                            Price = 1199m,
                            Type = 5,
                            WattageCapacity = 1000
                        },
                        new
                        {
                            Id = 60,
                            Brand = "Cooler Master",
                            Description = "Air cooler, suporte AM4/AM5/LGA1700",
                            IsAvailable = true,
                            Name = "Hyper 212 Black",
                            PowerConsumption = 5,
                            Price = 199m,
                            TDP = 150,
                            Type = 6
                        },
                        new
                        {
                            Id = 61,
                            Brand = "Noctua",
                            Description = "Dual tower, silencioso, top tier air",
                            IsAvailable = true,
                            Name = "NH-D15",
                            PowerConsumption = 5,
                            Price = 599m,
                            TDP = 250,
                            Type = 6
                        },
                        new
                        {
                            Id = 62,
                            Brand = "NZXT",
                            Description = "AIO 240mm, RGB, alto desempenho",
                            IsAvailable = true,
                            Name = "Kraken X63 240mm",
                            PowerConsumption = 8,
                            Price = 699m,
                            TDP = 250,
                            Type = 6
                        },
                        new
                        {
                            Id = 63,
                            Brand = "Corsair",
                            Description = "AIO 360mm, iCUE RGB, workstation/overclock",
                            IsAvailable = true,
                            Name = "H150i Elite 360mm",
                            PowerConsumption = 10,
                            Price = 1099m,
                            TDP = 350,
                            Type = 6
                        });
                });

            modelBuilder.Entity("PCBuilder.Models.BuildComponent", b =>
                {
                    b.HasOne("PCBuilder.Models.Build", "Build")
                        .WithMany("Components")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCBuilder.Models.Product", "Product")
                        .WithMany("BuildComponents")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PCBuilder.Models.OrderItem", b =>
                {
                    b.HasOne("PCBuilder.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCBuilder.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PCBuilder.Models.Build", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PCBuilder.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PCBuilder.Models.Product", b =>
                {
                    b.Navigation("BuildComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
